import { CarouselData } from './types';

export const defaultCarouselData: CarouselData = {
  id: 'trending-ai-repos-week-38',
  topic: "This Week's Trending GitHub Repos",
  coverTitle: '5 insane open-source tools',
  coverTitleAccent: 'you need to try.',
  coverSubtitle: 'These 5 repositories are blowing up right now. Hand-picked for maximum developer productivity.',
  editionBadge: 'WEEKLY GITHUB REPORT',
  theme: 'editorial-cream',
  settings: {
    maxRepos: 5,
    showSwipeHints: true,
    aspectRatio: 'vertical-9-16', // TikTok & Instagram default
    buttonStyle: 'pill-capsule',
  },
  repos: [
    {
      id: 'repo-1',
      index: 1,
      repoName: 'ai-job-search',
      author: 'MadsLorentzen',
      fullRepo: 'MadsLorentzen/ai-job-search',
      headlineLead: 'It applies to jobs',
      headlineAccent: 'while you sleep.',
      summary: 'It reads job postings, tailors your CV to each one, writes the cover letter and preps you for the interview.',
      punchline: 'Runs on your own machine, off Claude Code.',
      cardDescription: 'AI job applications, built on Claude Code.',
      language: 'TypeScript',
      languageColor: '#3178C6',
      stars: '22,818',
      forks: '7,110',
      badge: 'free',
      githubUrl: 'https://github.com/MadsLorentzen/ai-job-search',
      cloneCommand: 'git clone github.com/MadsLorentzen/ai-job-search',
      useCases: ['Tailor CV and portfolio to job description', 'Automate company background research'],
    },
    {
      id: 'repo-2',
      index: 2,
      repoName: 'DesktopCommanderMCP',
      author: 'wonderwhy-er',
      fullRepo: 'wonderwhy-er/DesktopCommanderMCP',
      headlineLead: 'Let Claude run',
      headlineAccent: 'your whole computer.',
      summary: 'It gives Claude control of your files and terminal, so it can search your machine, edit code and actually run things.',
      punchline: 'The one that makes Claude do stuff.',
      cardDescription: 'Give Claude terminal + file control (MCP).',
      language: 'TypeScript',
      languageColor: '#3178C6',
      stars: '8,300',
      forks: '1,006',
      badge: 'free',
      githubUrl: 'https://github.com/wonderwhy-er/DesktopCommanderMCP',
      cloneCommand: 'git clone github.com/wonderwhy-er/DesktopCommanderMCP',
      useCases: ['Autonomous code debugging across files', 'Search and organize desktop projects'],
    },
    {
      id: 'repo-3',
      index: 3,
      repoName: 'OfficeCLI',
      author: 'iOfficeAI',
      fullRepo: 'iOfficeAI/OfficeCLI',
      headlineLead: 'Run Word & Excel',
      headlineAccent: 'from terminal.',
      summary: 'Automate spreadsheets, generate PowerPoint slide decks, and update tables without touching a mouse.',
      punchline: 'Headless Office documents with simple scripts.',
      cardDescription: 'Terminal automation for Office documents.',
      language: 'Python',
      languageColor: '#3572A5',
      stars: '12,450',
      forks: '1,280',
      badge: 'free',
      githubUrl: 'https://github.com/iOfficeAI/OfficeCLI',
      cloneCommand: 'git clone github.com/iOfficeAI/OfficeCLI',
      useCases: ['Bulk spreadsheet data transformations', 'Instant PPT report generation from markdown'],
    },
    {
      id: 'repo-4',
      index: 4,
      repoName: 'hallmark',
      author: 'Nutlope',
      fullRepo: 'Nutlope/hallmark',
      headlineLead: 'Build landing pages',
      headlineAccent: 'in seconds.',
      summary: 'Prompt an AI agent to build clean, responsive React components with Tailwind CSS and one-click code export.',
      punchline: 'Instant production UI generation for builders.',
      cardDescription: 'AI landing page builder with live preview.',
      language: 'TypeScript',
      languageColor: '#3178C6',
      stars: '16,920',
      forks: '2,450',
      badge: 'free',
      githubUrl: 'https://github.com/Nutlope/hallmark',
      cloneCommand: 'git clone github.com/Nutlope/hallmark',
      useCases: ['One-click landing page mockups', 'Production-ready Tailwind & React components'],
    },
    {
      id: 'repo-5',
      index: 5,
      repoName: 'OmniRoute',
      author: 'diegosouzapw',
      fullRepo: 'diegosouzapw/OmniRoute',
      headlineLead: 'Switch between LLMs',
      headlineAccent: 'with zero latency.',
      summary: 'Smart routing proxy that balances requests across OpenAI, Gemini, Claude, and local Ollama models with automatic fallbacks.',
      punchline: 'Unified API gateway for all AI models.',
      cardDescription: 'High-performance multi-LLM proxy & router.',
      language: 'Rust',
      languageColor: '#DEA584',
      stars: '11,340',
      forks: '980',
      badge: 'free',
      githubUrl: 'https://github.com/diegosouzapw/OmniRoute',
      cloneCommand: 'git clone github.com/diegosouzapw/OmniRoute',
      useCases: ['Zero-downtime model failovers', 'Cost routing between fast & reasoning models'],
    },
  ],
  installSlide: {
    titleLead: 'How to',
    titleAccent: 'install.',
    description: "You can clone these in the terminal with git clone. But if it's your first time, paste them into any AI coding agent - Cursor, ChatGPT, Gemini or Claude - and it'll check each repo over and set it up for you.",
    cloneHighlightRepo: 'MadsLorentzen/ai-job-search',
    agentPromptText: 'check these are legit, then set them up:',
    ctaTextLead: "Save it now, you'll want this",
    ctaTextAccent: 'list later.',
    followButtonText: '+ FOLLOW',
    saveButtonText: 'SAVE THIS',
    buttonStyle: 'pill-capsule',
    agentTip: 'Works with Cursor • Claude 3.7 • ChatGPT • Gemini',
  },
};

export const presetCarousels: { name: string; description: string; data: CarouselData }[] = [
  {
    name: 'Willy Westside Trending Repos (Screenshot Replica)',
    description: "Exact 5-repo viral showcase from Willy Westside's TikTok carousel",
    data: defaultCarouselData,
  },
  {
    name: 'Terminal & CLI Utilities',
    description: 'Blazing fast developer utilities and TUI tools',
    data: {
      ...defaultCarouselData,
      id: 'terminal-dev-tools',
      topic: 'Top 5 Terminal Power Tools',
      coverTitle: '5 terminal utilities that make you',
      coverTitleAccent: 'feel like a 10x dev.',
      coverSubtitle: 'Ditch bloated desktop software for these ultra-fast command-line tools.',
      repos: [
        {
          id: 'repo-1',
          index: 1,
          repoName: 'superfile',
          author: 'yorukot',
          fullRepo: 'yorukot/superfile',
          headlineLead: 'Terminal file manager',
          headlineAccent: 'at lightspeed.',
          summary: 'Modern terminal file manager with syntax highlighting, dual-pane layout, and instant directory previews.',
          punchline: 'Goodbye Finder, hello lightning navigation.',
          cardDescription: 'Modern terminal file manager for devs.',
          language: 'Go',
          languageColor: '#00ADD8',
          stars: '14,200',
          forks: '540',
          badge: 'free',
          githubUrl: 'https://github.com/yorukot/superfile',
          cloneCommand: 'git clone github.com/yorukot/superfile',
          useCases: ['Fast dual-pane directory inspection', 'Batch file management with vim keys'],
        },
        {
          id: 'repo-2',
          index: 2,
          repoName: 'lazygit',
          author: 'jesseduffield',
          fullRepo: 'jesseduffield/lazygit',
          headlineLead: 'Git commands without',
          headlineAccent: 'the headache.',
          summary: 'Simple terminal UI for git commands that lets you stash, resolve conflicts, and squash commits in 2 keystrokes.',
          punchline: 'The terminal tool every senior dev swears by.',
          cardDescription: 'Simple terminal UI for git commands.',
          language: 'Go',
          languageColor: '#00ADD8',
          stars: '54,900',
          forks: '2,100',
          badge: 'free',
          githubUrl: 'https://github.com/jesseduffield/lazygit',
          cloneCommand: 'git clone github.com/jesseduffield/lazygit',
          useCases: ['Visual interactive rebasing', 'Instant conflict resolution in terminal'],
        },
        {
          id: 'repo-3',
          index: 3,
          repoName: 'ripgrep',
          author: 'BurntSushi',
          fullRepo: 'BurntSushi/ripgrep',
          headlineLead: 'Search 1,000,000 lines',
          headlineAccent: 'in 0.02 seconds.',
          summary: 'Line-oriented search tool that recursively searches your current directory for regex patterns faster than grep.',
          punchline: 'Written in Rust with zero regex engine overhead.',
          cardDescription: 'Ultra-fast search utility that respects gitignore.',
          language: 'Rust',
          languageColor: '#DEA584',
          stars: '48,100',
          forks: '2,300',
          badge: 'free',
          githubUrl: 'https://github.com/BurntSushi/ripgrep',
          cloneCommand: 'git clone github.com/BurntSushi/ripgrep',
          useCases: ['Instant codebase full-text search', 'Regex pattern matching across large repos'],
        },
      ],
      installSlide: {
        ...defaultCarouselData.installSlide,
        cloneHighlightRepo: 'yorukot/superfile',
      },
    },
  },
];
