export interface ThemeStyle {
  id: string;
  name: string;
  isDark: boolean;
  bgClass: string;
  bgHex: string;
  textClass: string;
  textHex: string;
  accentClass: string;
  accentHex: string;
  cardBgClass: string;
  cardBgHex: string;
  cardBorderClass: string;
  terminalBgClass: string;
  terminalTextClass: string;
  serifFont: string;
  codeFont: string;
  defaultBgEffect?: 'none' | 'colorful-splash' | 'aurora-glow' | 'studio-spotlight' | 'subtle-grid';
}

export const THEME_STYLES: Record<string, ThemeStyle> = {
  'designer-splash': {
    id: 'designer-splash',
    name: 'Designer Studio Splash (Vibrant Mesh)',
    isDark: true,
    bgClass: 'bg-[#090A10]',
    bgHex: '#090A10',
    textClass: 'text-slate-100',
    textHex: '#F8FAFC',
    accentClass: 'text-[#FF3366]',
    accentHex: '#FF3366',
    cardBgClass: 'bg-[#121422]/90 backdrop-blur-md',
    cardBgHex: '#121422',
    cardBorderClass: 'border-[#FF3366]/30',
    terminalBgClass: 'bg-[#05060A]',
    terminalTextClass: 'text-[#FDA4AF]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
    defaultBgEffect: 'colorful-splash',
  },
  'aurora-prism': {
    id: 'aurora-prism',
    name: 'Prism Studio (Light Creative Aurora)',
    isDark: false,
    bgClass: 'bg-[#FAF8FE]',
    bgHex: '#FAF8FE',
    textClass: 'text-[#0F172A]',
    textHex: '#0F172A',
    accentClass: 'text-[#6366F1]',
    accentHex: '#6366F1',
    cardBgClass: 'bg-white/95 backdrop-blur-md',
    cardBgHex: '#FFFFFF',
    cardBorderClass: 'border-[#E0E7FF]',
    terminalBgClass: 'bg-[#1E1B4B]',
    terminalTextClass: 'text-[#C7D2FE]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
    defaultBgEffect: 'colorful-splash',
  },
  'editorial-cream': {
    id: 'editorial-cream',
    name: 'Willy Editorial Cream (TikTok Viral)',
    isDark: false,
    bgClass: 'bg-[#FBF9F4]',
    bgHex: '#FBF9F4',
    textClass: 'text-[#1C1917]',
    textHex: '#1C1917',
    accentClass: 'text-[#E05A2B]',
    accentHex: '#E05A2B',
    cardBgClass: 'bg-white',
    cardBgHex: '#FFFFFF',
    cardBorderClass: 'border-[#E7E3D8]',
    terminalBgClass: 'bg-[#18181B]',
    terminalTextClass: 'text-[#F4F4F5]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'dark-neo': {
    id: 'dark-neo',
    name: 'Dark Neo Cyber',
    isDark: true,
    bgClass: 'bg-[#090D16]',
    bgHex: '#090D16',
    textClass: 'text-slate-100',
    textHex: '#F8FAFC',
    accentClass: 'text-indigo-400',
    accentHex: '#818CF8',
    cardBgClass: 'bg-slate-900/90',
    cardBgHex: '#0F172A',
    cardBorderClass: 'border-slate-800',
    terminalBgClass: 'bg-[#030712]',
    terminalTextClass: 'text-indigo-300',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'cyber-slate': {
    id: 'cyber-slate',
    name: 'Cyber Slate & Cyan',
    isDark: true,
    bgClass: 'bg-[#0B132B]',
    bgHex: '#0B132B',
    textClass: 'text-cyan-50',
    textHex: '#F0FDFA',
    accentClass: 'text-cyan-400',
    accentHex: '#22D3EE',
    cardBgClass: 'bg-[#1C2541]',
    cardBgHex: '#1C2541',
    cardBorderClass: 'border-cyan-900/50',
    terminalBgClass: 'bg-[#050A18]',
    terminalTextClass: 'text-cyan-300',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'sunset-minimal': {
    id: 'sunset-minimal',
    name: 'Warm Sunset Glow',
    isDark: false,
    bgClass: 'bg-[#FFF7ED]',
    bgHex: '#FFF7ED',
    textClass: 'text-[#431407]',
    textHex: '#431407',
    accentClass: 'text-[#EA580C]',
    accentHex: '#EA580C',
    cardBgClass: 'bg-white',
    cardBgHex: '#FFFFFF',
    cardBorderClass: 'border-orange-200',
    terminalBgClass: 'bg-[#1C1917]',
    terminalTextClass: 'text-orange-200',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'monochrome': {
    id: 'monochrome',
    name: 'Terminal Matrix Black',
    isDark: true,
    bgClass: 'bg-[#000000]',
    bgHex: '#000000',
    textClass: 'text-emerald-50',
    textHex: '#ECFDF5',
    accentClass: 'text-emerald-400',
    accentHex: '#34D399',
    cardBgClass: 'bg-[#0A0A0A]',
    cardBgHex: '#0A0A0A',
    cardBorderClass: 'border-emerald-950',
    terminalBgClass: 'bg-[#050505]',
    terminalTextClass: 'text-emerald-400',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'neon-cyberpunk': {
    id: 'neon-cyberpunk',
    name: 'Neon Cyberpunk (Electric Lime)',
    isDark: true,
    bgClass: 'bg-[#080C14]',
    bgHex: '#080C14',
    textClass: 'text-slate-100',
    textHex: '#F1F5F9',
    accentClass: 'text-[#10E57A]',
    accentHex: '#10E57A',
    cardBgClass: 'bg-[#0F172A]',
    cardBgHex: '#0F172A',
    cardBorderClass: 'border-[#10E57A]/30',
    terminalBgClass: 'bg-[#040711]',
    terminalTextClass: 'text-[#10E57A]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'luxury-gold': {
    id: 'luxury-gold',
    name: 'Matte Luxury Gold & Charcoal',
    isDark: true,
    bgClass: 'bg-[#0C0D0F]',
    bgHex: '#0C0D0F',
    textClass: 'text-[#F5F5F0]',
    textHex: '#F5F5F0',
    accentClass: 'text-[#E2BA76]',
    accentHex: '#E2BA76',
    cardBgClass: 'bg-[#15171C]',
    cardBgHex: '#15171C',
    cardBorderClass: 'border-[#2E2A24]',
    terminalBgClass: 'bg-[#08090A]',
    terminalTextClass: 'text-[#E2BA76]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'tokyo-night': {
    id: 'tokyo-night',
    name: 'Tokyo Night (Magenta & Indigo)',
    isDark: true,
    bgClass: 'bg-[#16161E]',
    bgHex: '#16161E',
    textClass: 'text-[#C0CAF5]',
    textHex: '#C0CAF5',
    accentClass: 'text-[#F7768E]',
    accentHex: '#F7768E',
    cardBgClass: 'bg-[#1F2335]',
    cardBgHex: '#1F2335',
    cardBorderClass: 'border-[#292E42]',
    terminalBgClass: 'bg-[#101017]',
    terminalTextClass: 'text-[#7AA2F7]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
  'nordic-frost': {
    id: 'nordic-frost',
    name: 'Nordic Frost (Clean Cobalt Studio)',
    isDark: false,
    bgClass: 'bg-[#F1F5F9]',
    bgHex: '#F1F5F9',
    textClass: 'text-[#0F172A]',
    textHex: '#0F172A',
    accentClass: 'text-[#2563EB]',
    accentHex: '#2563EB',
    cardBgClass: 'bg-white',
    cardBgHex: '#FFFFFF',
    cardBorderClass: 'border-[#CBD5E1]',
    terminalBgClass: 'bg-[#0F172A]',
    terminalTextClass: 'text-[#93C5FD]',
    serifFont: 'font-serif',
    codeFont: 'font-mono',
  },
};
